### PR TITLE
Fix disappearing rulers

### LINKED ISSUE #511: Findings related with parser
- [x] (1) Resolve false-positives:  green  code in editor: SQL builtins, host variables, CICS, etc 
 
- [x] (2) Host variables bug fixes related to (paranthesis, dimension range, )
 
- [x] (3) Missing implementation for host variables 'Result set locators' and 'Result set Table locators'

- [x] (4) Missing validations for (all host-variable arrays in PL/I) host variables  in dimension range. 
Will be done LATER.   

     ` DCL (c7(100), c8(400000)) Character(15); /*dimension range 1–32767*/`

- [x] (5) Grammar error in binary host-variable arrays 
               ` DCL b_ARRAY(100) SQL TYPE IS bin; /*ERR*/`
 
- [x] (6) Hover overs support (for SQLCA and SQLDA, struct variables)

- [x] (7) Bug fixes related to quick fix 

   a. once renaming .plugin folder quick fix does not resolve,)
   b. if copybook is not found in workspace, or defined absolute path error message should be 'NOT FOUND'  not 'Can not be opened' 
   c. if program uses variable from other copybooks, it resolves it as implicit variable,  but after a while, or after reloading it then recognizes it as declared variable 

- [x] (8) Large file

 
             a) include not processed as PL/I [single threaded issue] 
             b) slow has performance issue 

- [x] (9) Pop-up dialogue on copybooks should have a) correct PATH name b) column should be 72 character, lines are OK

 

- [x] (10) Issue with compound dataset resolution e.g. %include "DIM1" is not resolved same as %include DIM1 

- [x] ( 11) Code suggestions and completions does not work properly 

- [x] (12) Vertical Ruler at column 73 is LOST sometimes 11. 

- [x] (13) MSG: Duplicate compiler option found for <TOKEN>  causes/hides many other issues

- [x] (14) MSG: String options is not recognized as a valid option keyword and is ignored. Reproduced in multiple forms.

- [x] (15) Resolve below sql-includes as normal build-ins SQLCA, SQLDA in code.  
 
EXEC SQL INCLUDE SQLCA;
EXEC SQL INCLUDE SQLDA;

- [x]  (16) INPUT & OUTPUT attributes of dataset declaration produce improper errors

### PR DESCRIPTION
**Pull request by ssmifi**
Fixes https://github.com/zowe/zowe-pli-language-support/issues/511 12

Fixes two issues with the rulers:
1. Under the assumption that the LS will resend the margin information, it got removed when a document is closed. However, if the document is still in the compilation unit, it will not be resend anymore until changed. The new implementation rather deactivates the rulers for this document but keeps them in storage. 
2. There is a race condition when writing and reading configurations simultaneously. When browsing through files, documents are closed and opened quickly enough. The opened document still sees the stale config and may not set new ruler information. Rather than relying on a complex sync, we just force a reset after a document was disabled. The rulers are calculated on every update, which arrive in order, so this simpler solution does the job.

The change also makes sure that an update is only triggered when a document was opened/closed that actually had margin information.

### CODE REVIEW

File: packages/vscode-extension/src/extension/decorators.ts [hunk 1]
```diff
@@ -149,12 +164,13 @@ export namespace MarginIndicatorDecorator {
...
 
-    if (rulers.length === existingRulers.length) {
+    if (rulers.length === existingRulers.length && !revalidate) {
       // If the rulers are the same, no need to update
       if (rulers.every((r, i) => r === existingRulers[i])) {
         return;
       }
     }
     config.update("rulers", rulers, vscode.ConfigurationTarget.Global, true);
+    revalidate = false;
```
Comment (msujew) [inline packages/vscode-extension/src/extension/decorators.ts]: Just to make sure we set the flag before the config update:

```suggestion
revalidate = false;
config.update("rulers", rulers, vscode.ConfigurationTarget.Global, true);
```

**Review by msujew — APPROVED** [review]
LGTM
