### PR TITLE
Fix ambiguity quick fix action

### LINKED ISSUE #636: Scoped quick fix
In below code, quick fix is enabled, but it should only provide scoped fix. 
Only its direct level. 

Image

### PR DESCRIPTION
**Pull request by Lotes**
Fixes #636 

There are two cases according to the nesting of a declare statement:

Case 1:

```
DCL X CHAR(300);
 DCL CT BIN FIXED(31);
 DCL 1 A BASED(ADDR(X)),
       5 B BIN FIXED(31),
       5 C (CT REFER(B)),
         10* CHAR(1);
 DCL 1 AA BASED(ADDR(X)),  //splitted into two or more statements
       5 B1,
         10 B BIN FIXED(31),
       5 B2,
         10 B BIN FIXED(31), 
        5 C (CT REFER(B));
```

Case 2:

```
 DCL X CHAR(300);
 DCL CT BIN FIXED(31);
 DCL 1 A BASED(ADDR(X)), //everything in one statement
       5 B BIN FIXED(31),
       5 C (CT REFER(B)),
         10* CHAR(1),
     1 AA BASED(ADDR(X)),
       5 B1,
         10 B BIN FIXED(31),
       5 B2,
         10 B BIN FIXED(31), 
        5 C (CT REFER(B));
```

In case 2 we need to take care of the original structure, where the quickfix action or reference is coming from.

### CODE REVIEW

**Comment by Lotes** [comment]
Would be cool to have a test for my two cases actually...

**Comment by msujew** [comment]
@Lotes I'm inclined to agree. Do you think it makes sense for you to take a look at https://github.com/zowe/zowe-pli-language-support/issues/484 before continuing on this PR?

**Comment by Lotes** [comment]
Waiting for #652

File: packages/language/test/test-builder.ts [hunk 1]
```diff
@@ -450,6 +450,21 @@ Available code actions for label "${label}" and URI "${uri}": ${codeActions.map(
...
+      (acc, [, actions]) => acc + actions.length,
+      0,
+    );
+    expect(
+      actualCount,
+      `Expected ${expectedCount} code actions at label "${label}", but found ${actualCount}.`,
+    ).toBe(expectedCount);
+  }
+
   private async getCodeActions(label: string) {
```
Comment (msujew) [inline packages/language/test/test-builder.ts:468]: Minor: I know this is from a previous PR, but please add proper type annotations to this method. I found it difficult to discern the return type from this function.

File: packages/language/test/fourslash-harness/harness-interface.ts [hunk 2]
```diff
@@ -179,11 +179,6 @@ export interface HarnessTesterInterface {
         | PLICode
         | PLICode[],
     ): void;
-    /**
-     * Expect that there are no code actions at the given label.
-     * @param label The label to expect no code actions at.
-     */
-    noCodeActions(label: Label): Promise<void>;
```
Comment (msujew) [inline packages/language/test/fourslash-harness/harness-interface.ts:186]: Minor: I would keep this, it makes the tests a bit easier to read IMO. It can just delegate to `expectCodeActionCountAt(label, 0)`.

**Review by msujew — APPROVED** [review]
Thanks, looks good to me 👍

File: packages/language/test/test-builder.ts (hunk 1 above)
Comment (Lotes) [reply packages/language/test/test-builder.ts:468]: Makes much sense, thx
