### PR TITLE
Fix IF and SELECT pp parser

### LINKED ISSUE #513: [Parser] `%` are sometimes optional in preprocessor
When the compiler explicitly expects another preprocessor unit, the `%` token becomes optional. Examples:

```
%IF 0 = 1 %THEN DO; // <- Would usually require a %
  PUT("HELLO");
%ELSE DO; // <- Would usually require a %
  PUT("WORLD");
%END;
```

This seemingly only applies to the true/false branches of if statements and the when/otherwise cases of the select statement.

### PR DESCRIPTION
**Pull request by msujew**
Closes https://github.com/zowe/zowe-pli-language-support/issues/513

Fixes two main points of our preprocessor parser:
1. "simple" if statements such as `%IF 1 %THEN; <emit some code>` had the wrong semantics. Essentially the `;` after `%THEN` acts as a null-statement, after which normal PLI code is supposed to go. This change adjusts the behavior to only allow "real" preprocessor statements to follow the `%THEN` keyword in the context of the if statement. (this one is difficult to explain)
2. The compiler makes the **first** `%` after the `%THEN` optional. Meaning that `%IF ... %THEN DO; ... %END;` and `%IF ... %THEN %DO; ... %END;` are the same. Adding the `%` is fine with the compiler, but it is not required.

### CODE REVIEW

**Comment by ssmifi** [comment]
I remember testing % earlier this year w.r.t. the do loops and logged some findings regarding %IF here https://github.com/zowe/zowe-pli-language-support/issues/311, esp. % being optional in several cases. Did you see/check these cases as well?
In this case, probably mainly if the % before the THEN is optional or not.

**Comment by msujew** [comment]
> I remember testing % earlier this year w.r.t. the do loops and logged some findings regarding %IF here https://github.com/zowe/zowe-pli-language-support/issues/311, esp. % being optional in several cases.

Ah, I see, that's good to know.

> In this case, probably mainly if the % before the THEN is optional or not.

Thanks for pointing that out. You're right, it looks like the `%` is optional.

**Comment by msujew** [comment]
@ssmifi I've also made the `%` for `THEN` optional. Thanks for the hint!

File: packages/language/src/parser/preprocessor-parser.ts [hunk 1]
```diff
@@ -97,14 +126,25 @@ function labels(state: ParserState): ast.LabelPrefix[] {
...
+  options: StatementParseOptions & { withEnd: false },
+): ast.Statement | null;
+export function commonStatement(
+  state: ParserState,
+  options: StatementParseOptions,
+): ast.Statement | ast.EndStatement | null;
+export function commonStatement(
+  state: ParserState,
+  options: StatementParseOptions,
 ): ast.Statement | ast.EndStatement | null {
```
Comment (ssmifi) [inline packages/language/src/parser/preprocessor-parser.ts:132]: _Minor_: The JSDoc seems to be outdated.

File: packages/language/test/fourslash-harness/harness-parser.ts [hunk 2]
```diff
@@ -71,7 +71,7 @@ class HarnessTestParser {
     private context: Context,
   ) {
     // Reverse it for performance reasons, faster to pop than shift
-    this.lines = text.split("\n").toReversed();
+    this.lines = text.split(/\r?\n/).toReversed();
```
Comment (ssmifi) [inline packages/language/test/fourslash-harness/harness-parser.ts:74]: _Question_: Is there a specific reason for this change? Would this allow all fourslash tests to be in CRLF format? There are specific tests that test for windows line endings with a \r escape character, e.g., in the margin preprocessor. Wouldn't it be less confusing if the tests stay in one format and explicitly test for different line endings if necessary (or automatically test for all line endings)?

File: packages/language/test/fourslash/preprocessor/select-statement-multiple-conditions.ts [hunk 3]
```diff
@@ -12,8 +12,8 @@
 /// <reference path="../framework.ts" />
 
 //// %SELECT;
-//// %WHEN (0, 1, 2) X
-//// %OTHERWISE Y
+//// %WHEN (0, 1, 2) DO; X %END;
+//// %OTHERWISE DO Y %END;
```
Comment (ssmifi) [inline packages/language/test/fourslash/preprocessor/select-statement-multiple-conditions.ts]: _Question_: Is the semicolon at the DO missing on purpose? Does this work because of the recovery?

File: packages/language/test/fourslash/preprocessor/simple-if-else.ts [hunk 4]
```diff
@@ -11,9 +11,11 @@
...
-//// %IF 0 %THEN
+//// %IF 0 %THEN DO;
 ////   dcl X fixed;
-//// %ELSE
+//// %END;
+//// %ELSE DO;
 ////   dcl Y fixed;
+//// %END;
 
 preprocessor.expectTokens(" dcl Y fixed;");
```
Comment (ssmifi) [inline packages/language/test/fourslash/preprocessor/simple-if-else.ts]: _Tiny_: We can remove the leading space here, can't we? (Same for -then -with-scan)

**Review by ssmifi — COMMENTED** [review]
Thanks, looks good to me. I just have two questions about the testing.

File: packages/language/test/fourslash/preprocessor/select-statement-multiple-conditions.ts (hunk 3 above)
Comment (msujew) [reply packages/language/test/fourslash/preprocessor/select-statement-multiple-conditions.ts]: No, not missing on purpose. Good catch :)

File: packages/language/test/fourslash-harness/harness-parser.ts (hunk 2 above)
Comment (msujew) [reply packages/language/test/fourslash-harness/harness-parser.ts:74]: IMO, I don't think that the line ending should matter for running the test. I've noticed that if I create a new file on windows (which automatically gets CRLF in VSCode), my tests start failing unexpectedly, because the lines aren't split correctly. Note that special characters such as `\r` in the test code will actually be stored as `\\r` and not be subject to changes due to this change.

**Review by ssmifi — APPROVED** [review]
👍
